spring:
  datasource-primary:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:6603/user?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  datasource-secondary:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:6603/employee?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  datasource-tertiary:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:6603/admin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id:
          new_generator_mappings: false
        show-sql: true
