server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

spring:
  application:
    name: service-registratrion-discovery-configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RafaelPacheco94/microservices-configuration-repository



