server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true

