server:
  port: 8083

spring:
  application:
    name: trader-sentiments
  profiles:
    active: dev
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true