server:
  port: 8088

spring:
  kafka:
    bootstrap-servers: localhost:29092
    listener:
      missing-topics-fatal: false
  application:
    name: kafka-producer

consumer:
  kafka:
    stock:
      topic-name-stock-list: stock-list
      topic-name-stock: stock
      topic-name-simple-message: simple-message
      group-name: group-id
